# Generated by Django 4.2.2 on 2023-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='id',
        ),
        migrations.AlterField(
            model_name='expense',
            name='item',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
