# Generated by Django 4.2.2 on 2023-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrack', '0002_remove_expense_id_alter_expense_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
